export const ROUTES = {
  LOGIN: "Login",
  SIGNUP: "Signup",
  HOME: "Home",
  CATEGORY: "Category",
  PRODUCT_DETAIL: "ProductDetail",
  CART: "Cart",
  ORDERS: "Orders",
  PROFILE: "Profile",
  EDIT_PROFILE: "EditProfile",
  SHOP_TAB: "ShopTab",
  CART_TAB: "CartTab",
  ORDERS_TAB: "OrdersTab",
  PROFILE_TAB: "ProfileTab",
};